language: java
dist: trusty
jdk:
  - oraclejdk8
script:
  - mvn clean install
  - sonar-scanner
addons:
  sonarqube:
  branches:
    - master
    - maintenance
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: false
